---
extends: default

rules:
  line-length:
    max: 120  # Keep this updated with the editorconfig file
    level: warning
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
