---
name: Clean Validation Environments

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: Dev
        required: true


jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    if: |
      github.ref != 'refs/heads/main'
    environment: Dev
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          # This is CRITICAL since we're making decisions based on branch existence
          fetch-depth: 0
          persist-credentials: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ (secrets.AZURE_ENVIRONMENT != '' && secrets.AZURE_ENVIRONMENT) || 'AzureCloud' }}

      - name: Run clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIN_TRE_ID: ${{ secrets.TRE_ID }}
          GITHUB_REPOSITORY: ${{ github.repository}}
          BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_STOP: 2
          BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_DESTROY: 48
        run: .github/scripts/clean_ci_validation_envs.sh
